### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-package-json-intro-AjvZZg#1]
@egillespie Can you take a look at this? It's [hosted here](https://kisyular-kg-tgc7noax99ajvzzg.surge.sh/) and meets the following criteria:

- [x] Start your project with [these old game files](https://gist.github.com/egillespie/61d72035cd8c2639f07db1dbe2010605)
- [x] Convert the game's CSS to Sass, using variables, functions, and nesting where appropriate
- [x] Write a `dev` script in `package.json` that auto-compiles Sass and refreshes the browser at the same time
- [x] Write a `build` script in `package.json` that lints HTML, Sass, and JavaScript files before compiling Sass files (you can use these linters: [htmlhint](https://www.npmjs.com/package/htmlhint) for HTML, [stylelint](https://www.npmjs.com/package/stylelint) and [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard#installation) for Sass, [standard](https://www.npmjs.com/package/standard) for JavaScript)
- [x] All linting problems are fixed (problems will be displayed in the terminal when you run `yarn build`)
- [x] Write a `deploy` script in `package.json` that builds the project and uploads it to Surge if there are no errors
- [x] Unnecessary files like `node_modules` and your compiled CSS do not exist in your repository
- [x] Unnecessary files like `package.json` and `yarn.lock` are not uploaded to Surge

**Comment by egillespie** [comment]
Hi @kisyular, this is off to a really good start. Do you mind making the following changes for me?

### Exclude `compiled` in `.gitignore`

Compiled files don't typically go in version control. Can you remove `compiled` from your repository and add that directory to `.gitignore`?

### Issues in `package.json`

There are numerous issues in `package.json`. Can you please run each script against your project, fix the errors associated with each one, and submit your changes back? Make sure every tool you use in your scripts is added as a dev dependency as well (for example, `htmlhint` and `standard` are missing. There's also no style linting in your file. Please add that.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🦁

**Comment by kisyular** [comment]
@egillespie 
Corrected the errors

**Comment by egillespie** [comment]
This looks great, @kisyular. I really appreciate all of the hard work you put into this! :shipit:
